name: Kritika Tyagi
education:
  degree: Master of Computer Applications (MCA)
  institution: AKT University
  graduation_year: 2019
experience:
  - role: Android App Developer
    company: Pawani Web Technology
    location: India
    start_date: Oct 2023
    end_date: Dec 2024
  - role: Android App Developer
    company: V&V Consulting Solutions LLP, Noida
    location: India
    start_date: Aug 2022
    end_date: Oct 2023
  - role: Python Developer
    company: Savatarr Technologies Pvt. Ltd., Noida
    location: India
    start_date: Jan 2020
    end_date: Aug 2022
projects:
  - name: My Next Music Online Play Store
    description: A secure, web-based music streaming and purchasing platform with user registration, robust verification, and secure transactions.
    technologies: [PHP, HTML, JavaScript, MySQL]
  - name: Board Marksheet
    description: A Java-based application allowing admins and teachers to manage student data, courses, and marks.
    technologies: [Java, MySQL]
  - name: Online Reservation System
    description: A Java-based software with an MS-Access database backend, designed for seamless hotel reservations, registration, billing, and checkout.
    technologies: [Java, MS-Access]
  - name: SmartClass App (Experifun/Eduvahini)
    description: A teaching and learning platform featuring live classes, assessments, grading, and notifications.
    technologies: [Java, Firebase]
    link: https://apps.apple.com/az/developer/experifun-educational-solutions-private-limited/id1607855038
  - name: HMS Online App
    description: A government hospital app designed for efficient patient management and monitoring.
    technologies: [Firebase]
    link: https://play.google.com/store/apps/details?id=co.martin.zxqee&pcampaignid=web_share
  - name: Online School Management System
    description: A PHP CodeIgniter-based system for managing students, teachers, classes, fees, attendance, exams, and schedules.
    technologies: [PHP, HTML, Bootstrap, MySQL]
  - name: Health and Monitoring Systems
    description: A mobile app designed for real-time health tracking, patient monitoring, and appointment scheduling.
    technologies: [Java, MySQL, Firebase]
skills:
  programming_languages: [Python, Java, Dart, Flutter]
  frameworks: [Android Studio, Firebase, CodeIgniter]
  frontend: [HTML, CSS, JavaScript]
  databases: [MySQL, Firebase, MS-Access]
  version_control: GitHub
  expertise: [UI/UX Design, Troubleshooting, Debugging, Code Optimization, Problem Solving, Mobile App Development]
  methodologies: Agile
certifications:
  - Python (Intermediate)
  - Java (Advanced)
  - Ethical Hacking (Professional)
  - Cyber Security & Real-time Projects (Professional)
language:
  - Hindi
  - English
contact:
  email: theroyalkritika@gmail.com
  phone: +91 8077492270
  linkedin: https://www.linkedin.com/in/kritika-tyagi-72b01022a
resume:
  file: /assets/Kritikatyagi.pdf
