profile:
    name: KRITIKA TYAGI
    label: Developer Android App | Flutter App
    email: theroyalkritika@gmail.com
    phone: +91 8077492270
    address: Ghaziabad, Uttar Pradesh, In
    summary: >
        I am a skilled Mobile Application Developer with 4 years of experience in Android and Flutter, combined with Python proficiency. I excel at creating intuitive, high-performance apps and solving complex challenges through innovative solutions. Skilled in designing seamless user experiences, refining code for efficiency, and adapting features based on real-world feedback, I thrive in environments that encourage growth and collaboration. Always eager to learn and innovate, I aim to contribute to projects that push the boundaries of technology.

    #image: "https://avatars2.githubusercontent.com/u/446998?v=2&s=460"
    #website: http://www.hanula.com

    networks:
        -   provider: github
            username: hanula
            url: https://github.com/thekritikatyagi

        -   provider: linkedin
            username: kritika-tyagi-72b01022a
            url: linkedin.com/in/kritika-tyagi-72b01022a

show_downloads: true
theme: jekyll-theme-minimal
pdf_file: assets/kritikatyagi.pdf
